# Generated by Django 5.0.6 on 2024-07-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_giftcertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCertificate',
        ),
    ]
