# Generated by Django 5.0.6 on 2024-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_delete_giftcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_data', models.TextField()),
            ],
        ),
    ]
