# Generated by Django 5.0.6 on 2024-07-24 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_supplychainforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
