# Generated by Django 5.0.6 on 2024-07-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
