# Generated by Django 5.0.6 on 2025-03-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
