# Generated by Django 5.0.6 on 2024-07-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_user_is_email_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
