# Generated by Django 5.0.6 on 2025-03-21 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='updated_at',
        ),
        migrations.AddField(
        model_name='productreview',
        name='id',
        field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        preserve_default=False,
    ),

    ]
